version: 2
updates:
  - package-ecosystem: pip
    directory: /back
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /front
    schedule:
      interval: monthly
    groups:
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
